# Nome do workflow, aparece na aba "Actions" do GitHub
name: Pipeline CI/CD

# Define quando o pipeline será disparado
on:
  push:
    branches:
      - main

    # Só dispara se arquivos nessas pastas/arquivos mudarem
    paths:
      - "src/**" # Mudanças no código-fonte
      - ".github/workflows/**" # Mudanças no próprio pipeline
      - "package.json" # Mudanças nas dependências/scripts
      - "package-lock.json" # Mudanças no lock das dependências

  # Habilita o botão "Run workflow" no GitHub Actions
  workflow_dispatch:

# Define os jobs que serão executados
jobs:

  # Primeiro job: realiza o build
  build:
    runs-on: ubuntu-latest # Máquina virtual usada no CI

    steps:

      # Baixa o código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # Instala e configura o Node.js
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Versão do Node.js utilizada
          cache: "npm" # Utiliza cache para acelerar a instalação
          cache-dependency-path: package-lock.json # Arquivo usado para o cache

      # Instala as dependências usando exatamente o package-lock.json
      - name: Instalação das dependências
        run: npm ci

      # Verifica se o projeto consegue ser compilado
      - name: Rodar o build
        run: npm run build


  # Segundo job: executa os testes
  tests:
    runs-on: ubuntu-latest # Máquina virtual usada no CI

    # Só executa depois que o job build terminar com sucesso
    needs: build

    steps:

      # Baixa o código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # Instala e configura o Node.js
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Instala as dependências do projeto
      - name: Instalação das dependências
        run: npm ci

      # Verifica problemas de lint no projeto
      - name: Verificar código
        run: npm run lint

      # Executa os testes automatizados com Jest
      - name: Rodar testes
        run: npm run test
