# Nome do workflow, aparece na aba "Actions" do GitHub
name: Pipeline CI/CD

# Define quando o pipeline será disparado
on:
  push:
    branches:
      - main

  # Habilita o botão "Run workflow" no GitHub Actions
  workflow_dispatch:

# Define os jobs que serão executados no pipeline
jobs:

  # Primeiro job: verifica a variável de ambiente
  check-env:
    runs-on: ubuntu-latest

    env:
      TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}

    steps:

      - name: Verificar variável de ambiente
        run: |
          if [ -z "$TMDB_TOKEN" ]; then
            echo "TMDB_TOKEN não está configurado no GitHub."
            exit 1
          fi

          echo "TMDB_TOKEN está configurado."


  # Segundo job: realiza o build do projeto
  build:
    runs-on: ubuntu-latest

    # Só executa se a variável de ambiente estiver configurada
    needs: check-env

    steps:

      # Baixa o código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # Instala e configura o Node.js
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Instala as dependências usando o package-lock.json
      - name: Instalação das dependências
        run: npm ci

      # Verifica se o projeto consegue ser compilado
      - name: Rodar o build
        run: npm run build


  # Terceiro job: verifica formatação e executa os testes
  tests:
    runs-on: ubuntu-latest

    # Só executa depois que o job build for concluído com sucesso
    needs: build

    steps:

      # Baixa o código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # Instala e configura o Node.js
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Instala as dependências do projeto
      - name: Instalação das dependências
        run: npm ci

      # Verifica se o código segue o padrão de formatação
      - name: Verificar Formatação
        run: npm run lint

      # Executa os testes automatizados com Jest
      - name: Rodar testes
        run: npm run test


  # Quarto job: faz o deploy
  deploy:
    runs-on: ubuntu-latest

    # Só executa depois que os testes passarem
    needs: tests

    steps:

      # Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Instala e configura o Node.js
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Instala a Vercel CLI
      - name: Instalação Vercel CLI
        run: npm install -g vercel@latest

      # Deploy para Vercel
      - name: Deploy para Vercel
        run: vercel --prod --yes --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.ORGID }}
          VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}
